// AUTO-GENERATED list of common job titles for people who use a screen-recording /
// collaboration tool. Used to seed the job-title autocomplete in the sign-up
// onboarding step. Users may also type a custom title not in this list.

export const JOB_TITLES: readonly string[] = [
  "Academic Advisor",
  "Account Executive",
  "Account Manager",
  "Accountant",
  "Agile Coach",
  "AI Engineer",
  "Analytics Engineer",
  "Android Engineer",
  "Art Director",
  "Associate Academic Advisor",
  "Associate Account Executive",
  "Associate Account Manager",
  "Associate Accountant",
  "Associate Agile Coach",
  "Associate AI Engineer",
  "Associate Analytics Engineer",
  "Associate Android Engineer",
  "Associate Art Director",
  "Associate Automation Engineer",
  "Associate Backend Engineer",
  "Associate BI Developer",
  "Associate Bookkeeper",
  "Associate Brand Designer",
  "Associate Brand Manager",
  "Associate Build Engineer",
  "Associate Business Analyst",
  "Associate Business Consultant",
  "Associate Business Development Representative",
  "Associate Business Operations Manager",
  "Associate Campaign Manager",
  "Associate Channel Manager",
  "Associate Chief of Staff",
  "Associate Cloud Engineer",
  "Associate Co-Founder",
  "Associate Communications Manager",
  "Associate Community Manager",
  "Associate Compliance Manager",
  "Associate Consultant",
  "Associate Content Creator",
  "Associate Content Marketer",
  "Associate Content Strategist",
  "Associate Content Writer",
  "Associate Contractor",
  "Associate Controller",
  "Associate Copywriter",
  "Associate Corporate Trainer",
  "Associate Course Creator",
  "Associate Creative Director",
  "Associate Curriculum Developer",
  "Associate Customer Experience Manager",
  "Associate Customer Service Representative",
  "Associate Customer Success Engineer",
  "Associate Customer Success Manager",
  "Associate Customer Support Specialist",
  "Associate Data Analyst",
  "Associate Data Architect",
  "Associate Data Engineer",
  "Associate Data Scientist",
  "Associate Database Administrator",
  "Associate Demand Generation Manager",
  "Associate Design Lead",
  "Associate Design Manager",
  "Associate Design Systems Designer",
  "Associate Developer Advocate",
  "Associate Developer Relations Manager",
  "Associate DevOps Engineer",
  "Associate Documentation Specialist",
  "Associate Editor",
  "Associate Education Consultant",
  "Associate Email Marketing Manager",
  "Associate Embedded Engineer",
  "Associate Engineering Manager",
  "Associate Enterprise Account Executive",
  "Associate Entrepreneur",
  "Associate Field Marketing Manager",
  "Associate Finance Manager",
  "Associate Financial Analyst",
  "Associate Firmware Engineer",
  "Associate Founder",
  "Associate Freelancer",
  "Associate Frontend Engineer",
  "Associate Full Stack Engineer",
  "Associate Game Developer",
  "Associate General Manager",
  "Associate Graphic Designer",
  "Associate Group Product Manager",
  "Associate Growth Marketer",
  "Associate Growth Product Manager",
  "Associate Help Desk Technician",
  "Associate HR Business Partner",
  "Associate HR Manager",
  "Associate Illustrator",
  "Associate Implementation Specialist",
  "Associate Inside Sales Representative",
  "Associate Insights Analyst",
  "Associate Instructional Designer",
  "Associate Instructor",
  "Associate Integration Engineer",
  "Associate Interaction Designer",
  "Associate Intern",
  "Associate iOS Engineer",
  "Associate Journalist",
  "Associate Knowledge Manager",
  "Associate Learning and Development Manager",
  "Associate Lecturer",
  "Associate Legal Counsel",
  "Associate Localization Manager",
  "Associate Machine Learning Engineer",
  "Associate Management Consultant",
  "Associate Marketing Manager",
  "Associate Marketing Operations Manager",
  "Associate Mobile Engineer",
  "Associate Motion Designer",
  "Associate Network Engineer",
  "Associate Office Manager",
  "Associate Onboarding Manager",
  "Associate Onboarding Specialist",
  "Associate Operations Analyst",
  "Associate Operations Manager",
  "Associate Owner",
  "Associate Paralegal",
  "Associate Partnerships Manager",
  "Associate Payroll Specialist",
  "Associate People Operations Manager",
  "Associate Performance Marketer",
  "Associate Platform Engineer",
  "Associate Podcast Producer",
  "Associate President",
  "Associate Product Analyst",
  "Associate Product Designer",
  "Associate Product Manager",
  "Associate Product Marketing Manager",
  "Associate Product Operations Manager",
  "Associate Product Owner",
  "Associate Professor",
  "Associate Program Manager",
  "Associate Project Manager",
  "Associate Public Relations Manager",
  "Associate QA Engineer",
  "Associate Quantitative Analyst",
  "Associate Recruiter",
  "Associate Release Engineer",
  "Associate Research Scientist",
  "Associate Researcher",
  "Associate Revenue Operations Manager",
  "Associate Sales Development Representative",
  "Associate Sales Director",
  "Associate Sales Engineer",
  "Associate Sales Manager",
  "Associate Sales Operations Manager",
  "Associate Sales Representative",
  "Associate School Administrator",
  "Associate Scrum Master",
  "Associate Security Engineer",
  "Associate SEO Specialist",
  "Associate Site Reliability Engineer",
  "Associate Social Media Manager",
  "Associate Software Architect",
  "Associate Software Engineer",
  "Associate Solutions Architect",
  "Associate Solutions Consultant",
  "Associate Solutions Engineer",
  "Associate Statistician",
  "Associate Strategy Manager",
  "Associate Support Engineer",
  "Associate Support Manager",
  "Associate Systems Engineer",
  "Associate Talent Acquisition Specialist",
  "Associate Teacher",
  "Associate Teaching Assistant",
  "Associate Technical Lead",
  "Associate Technical Product Manager",
  "Associate Technical Program Manager",
  "Associate Technical Recruiter",
  "Associate Technical Support Engineer",
  "Associate Technical Writer",
  "Associate Test Engineer",
  "Associate Trainer",
  "Associate Translator",
  "Associate Tutor",
  "Associate UI Designer",
  "Associate UX Designer",
  "Associate UX Researcher",
  "Associate Video Editor",
  "Associate Video Producer",
  "Associate Visual Designer",
  "Associate Web Designer",
  "Associate Web Developer",
  "Automation Engineer",
  "Backend Engineer",
  "BI Developer",
  "Bookkeeper",
  "Brand Designer",
  "Brand Manager",
  "Build Engineer",
  "Business Analyst",
  "Business Consultant",
  "Business Development Representative",
  "Business Operations Manager",
  "Campaign Manager",
  "Channel Manager",
  "Chief Academic Advisor",
  "Chief Account Executive",
  "Chief Account Manager",
  "Chief Accountant",
  "Chief Agile Coach",
  "Chief AI Engineer",
  "Chief Analytics Engineer",
  "Chief Android Engineer",
  "Chief Art Director",
  "Chief Automation Engineer",
  "Chief Backend Engineer",
  "Chief BI Developer",
  "Chief Bookkeeper",
  "Chief Brand Designer",
  "Chief Brand Manager",
  "Chief Build Engineer",
  "Chief Business Analyst",
  "Chief Business Consultant",
  "Chief Business Development Representative",
  "Chief Business Operations Manager",
  "Chief Campaign Manager",
  "Chief Channel Manager",
  "Chief Chief of Staff",
  "Chief Cloud Engineer",
  "Chief Co-Founder",
  "Chief Communications Manager",
  "Chief Community Manager",
  "Chief Compliance Manager",
  "Chief Consultant",
  "Chief Content Creator",
  "Chief Content Marketer",
  "Chief Content Strategist",
  "Chief Content Writer",
  "Chief Contractor",
  "Chief Controller",
  "Chief Copywriter",
  "Chief Corporate Trainer",
  "Chief Course Creator",
  "Chief Creative Director",
  "Chief Curriculum Developer",
  "Chief Customer Experience Manager",
  "Chief Customer Officer",
  "Chief Customer Service Representative",
  "Chief Customer Success Engineer",
  "Chief Customer Success Manager",
  "Chief Customer Support Specialist",
  "Chief Data Analyst",
  "Chief Data Architect",
  "Chief Data Engineer",
  "Chief Data Officer",
  "Chief Data Scientist",
  "Chief Database Administrator",
  "Chief Demand Generation Manager",
  "Chief Design Lead",
  "Chief Design Manager",
  "Chief Design Officer",
  "Chief Design Systems Designer",
  "Chief Developer Advocate",
  "Chief Developer Relations Manager",
  "Chief DevOps Engineer",
  "Chief Documentation Specialist",
  "Chief Editor",
  "Chief Education Consultant",
  "Chief Email Marketing Manager",
  "Chief Embedded Engineer",
  "Chief Engineering Manager",
  "Chief Enterprise Account Executive",
  "Chief Entrepreneur",
  "Chief Executive Officer",
  "Chief Field Marketing Manager",
  "Chief Finance Manager",
  "Chief Financial Analyst",
  "Chief Financial Officer",
  "Chief Firmware Engineer",
  "Chief Founder",
  "Chief Freelancer",
  "Chief Frontend Engineer",
  "Chief Full Stack Engineer",
  "Chief Game Developer",
  "Chief General Manager",
  "Chief Graphic Designer",
  "Chief Group Product Manager",
  "Chief Growth Marketer",
  "Chief Growth Product Manager",
  "Chief Help Desk Technician",
  "Chief HR Business Partner",
  "Chief HR Manager",
  "Chief Illustrator",
  "Chief Implementation Specialist",
  "Chief Information Officer",
  "Chief Information Security Officer",
  "Chief Inside Sales Representative",
  "Chief Insights Analyst",
  "Chief Instructional Designer",
  "Chief Instructor",
  "Chief Integration Engineer",
  "Chief Interaction Designer",
  "Chief Intern",
  "Chief iOS Engineer",
  "Chief Journalist",
  "Chief Knowledge Manager",
  "Chief Learning and Development Manager",
  "Chief Lecturer",
  "Chief Legal Counsel",
  "Chief Localization Manager",
  "Chief Machine Learning Engineer",
  "Chief Management Consultant",
  "Chief Marketing Manager",
  "Chief Marketing Officer",
  "Chief Marketing Operations Manager",
  "Chief Mobile Engineer",
  "Chief Motion Designer",
  "Chief Network Engineer",
  "Chief of Staff",
  "Chief Office Manager",
  "Chief Onboarding Manager",
  "Chief Onboarding Specialist",
  "Chief Operating Officer",
  "Chief Operations Analyst",
  "Chief Operations Manager",
  "Chief Owner",
  "Chief Paralegal",
  "Chief Partnerships Manager",
  "Chief Payroll Specialist",
  "Chief People Officer",
  "Chief People Operations Manager",
  "Chief Performance Marketer",
  "Chief Platform Engineer",
  "Chief Podcast Producer",
  "Chief President",
  "Chief Product Analyst",
  "Chief Product Designer",
  "Chief Product Manager",
  "Chief Product Marketing Manager",
  "Chief Product Officer",
  "Chief Product Operations Manager",
  "Chief Product Owner",
  "Chief Professor",
  "Chief Program Manager",
  "Chief Project Manager",
  "Chief Public Relations Manager",
  "Chief QA Engineer",
  "Chief Quantitative Analyst",
  "Chief Recruiter",
  "Chief Release Engineer",
  "Chief Research Scientist",
  "Chief Researcher",
  "Chief Revenue Officer",
  "Chief Revenue Operations Manager",
  "Chief Sales Development Representative",
  "Chief Sales Director",
  "Chief Sales Engineer",
  "Chief Sales Manager",
  "Chief Sales Operations Manager",
  "Chief Sales Representative",
  "Chief School Administrator",
  "Chief Scrum Master",
  "Chief Security Engineer",
  "Chief SEO Specialist",
  "Chief Site Reliability Engineer",
  "Chief Social Media Manager",
  "Chief Software Architect",
  "Chief Software Engineer",
  "Chief Solutions Architect",
  "Chief Solutions Consultant",
  "Chief Solutions Engineer",
  "Chief Statistician",
  "Chief Strategy Manager",
  "Chief Strategy Officer",
  "Chief Support Engineer",
  "Chief Support Manager",
  "Chief Systems Engineer",
  "Chief Talent Acquisition Specialist",
  "Chief Teacher",
  "Chief Teaching Assistant",
  "Chief Technical Lead",
  "Chief Technical Product Manager",
  "Chief Technical Program Manager",
  "Chief Technical Recruiter",
  "Chief Technical Support Engineer",
  "Chief Technical Writer",
  "Chief Technology Officer",
  "Chief Test Engineer",
  "Chief Trainer",
  "Chief Translator",
  "Chief Tutor",
  "Chief UI Designer",
  "Chief UX Designer",
  "Chief UX Researcher",
  "Chief Video Editor",
  "Chief Video Producer",
  "Chief Visual Designer",
  "Chief Web Designer",
  "Chief Web Developer",
  "Cloud Engineer",
  "Co-Founder",
  "Communications Manager",
  "Community Manager",
  "Compliance Manager",
  "Consultant",
  "Content Creator",
  "Content Marketer",
  "Content Strategist",
  "Content Writer",
  "Contractor",
  "Controller",
  "Copywriter",
  "Corporate Trainer",
  "Course Creator",
  "Creative Director",
  "Curriculum Developer",
  "Customer Experience Manager",
  "Customer Service Representative",
  "Customer Success Engineer",
  "Customer Success Manager",
  "Customer Support Specialist",
  "Data Analyst",
  "Data Architect",
  "Data Engineer",
  "Data Scientist",
  "Database Administrator",
  "Demand Generation Manager",
  "Design Lead",
  "Design Manager",
  "Design Systems Designer",
  "Developer Advocate",
  "Developer Relations Manager",
  "DevOps Engineer",
  "Director of Academic Advisor",
  "Director of Account Executive",
  "Director of Account Manager",
  "Director of Accountant",
  "Director of Agile Coach",
  "Director of AI Engineer",
  "Director of Analytics Engineer",
  "Director of Android Engineer",
  "Director of Art Director",
  "Director of Automation Engineer",
  "Director of Backend Engineer",
  "Director of BI Developer",
  "Director of Bookkeeper",
  "Director of Brand Designer",
  "Director of Brand Manager",
  "Director of Build Engineer",
  "Director of Business Analyst",
  "Director of Business Consultant",
  "Director of Business Development Representative",
  "Director of Business Operations Manager",
  "Director of Campaign Manager",
  "Director of Channel Manager",
  "Director of Chief of Staff",
  "Director of Cloud Engineer",
  "Director of Co-Founder",
  "Director of Communications Manager",
  "Director of Community Manager",
  "Director of Compliance Manager",
  "Director of Consultant",
  "Director of Content Creator",
  "Director of Content Marketer",
  "Director of Content Strategist",
  "Director of Content Writer",
  "Director of Contractor",
  "Director of Controller",
  "Director of Copywriter",
  "Director of Corporate Trainer",
  "Director of Course Creator",
  "Director of Creative Director",
  "Director of Curriculum Developer",
  "Director of Customer Experience Manager",
  "Director of Customer Service Representative",
  "Director of Customer Success Engineer",
  "Director of Customer Success Manager",
  "Director of Customer Support Specialist",
  "Director of Data Analyst",
  "Director of Data Architect",
  "Director of Data Engineer",
  "Director of Data Scientist",
  "Director of Database Administrator",
  "Director of Demand Generation Manager",
  "Director of Design Lead",
  "Director of Design Manager",
  "Director of Design Systems Designer",
  "Director of Developer Advocate",
  "Director of Developer Relations Manager",
  "Director of DevOps Engineer",
  "Director of Documentation Specialist",
  "Director of Editor",
  "Director of Education Consultant",
  "Director of Email Marketing Manager",
  "Director of Embedded Engineer",
  "Director of Engineering Manager",
  "Director of Enterprise Account Executive",
  "Director of Entrepreneur",
  "Director of Field Marketing Manager",
  "Director of Finance Manager",
  "Director of Financial Analyst",
  "Director of Firmware Engineer",
  "Director of Founder",
  "Director of Freelancer",
  "Director of Frontend Engineer",
  "Director of Full Stack Engineer",
  "Director of Game Developer",
  "Director of General Manager",
  "Director of Graphic Designer",
  "Director of Group Product Manager",
  "Director of Growth Marketer",
  "Director of Growth Product Manager",
  "Director of Help Desk Technician",
  "Director of HR Business Partner",
  "Director of HR Manager",
  "Director of Illustrator",
  "Director of Implementation Specialist",
  "Director of Inside Sales Representative",
  "Director of Insights Analyst",
  "Director of Instructional Designer",
  "Director of Instructor",
  "Director of Integration Engineer",
  "Director of Interaction Designer",
  "Director of Intern",
  "Director of iOS Engineer",
  "Director of Journalist",
  "Director of Knowledge Manager",
  "Director of Learning and Development Manager",
  "Director of Lecturer",
  "Director of Legal Counsel",
  "Director of Localization Manager",
  "Director of Machine Learning Engineer",
  "Director of Management Consultant",
  "Director of Marketing Manager",
  "Director of Marketing Operations Manager",
  "Director of Mobile Engineer",
  "Director of Motion Designer",
  "Director of Network Engineer",
  "Director of Office Manager",
  "Director of Onboarding Manager",
  "Director of Onboarding Specialist",
  "Director of Operations Analyst",
  "Director of Operations Manager",
  "Director of Owner",
  "Director of Paralegal",
  "Director of Partnerships Manager",
  "Director of Payroll Specialist",
  "Director of People Operations Manager",
  "Director of Performance Marketer",
  "Director of Platform Engineer",
  "Director of Podcast Producer",
  "Director of President",
  "Director of Product Analyst",
  "Director of Product Designer",
  "Director of Product Manager",
  "Director of Product Marketing Manager",
  "Director of Product Operations Manager",
  "Director of Product Owner",
  "Director of Professor",
  "Director of Program Manager",
  "Director of Project Manager",
  "Director of Public Relations Manager",
  "Director of QA Engineer",
  "Director of Quantitative Analyst",
  "Director of Recruiter",
  "Director of Release Engineer",
  "Director of Research Scientist",
  "Director of Researcher",
  "Director of Revenue Operations Manager",
  "Director of Sales Development Representative",
  "Director of Sales Director",
  "Director of Sales Engineer",
  "Director of Sales Manager",
  "Director of Sales Operations Manager",
  "Director of Sales Representative",
  "Director of School Administrator",
  "Director of Scrum Master",
  "Director of Security Engineer",
  "Director of SEO Specialist",
  "Director of Site Reliability Engineer",
  "Director of Social Media Manager",
  "Director of Software Architect",
  "Director of Software Engineer",
  "Director of Solutions Architect",
  "Director of Solutions Consultant",
  "Director of Solutions Engineer",
  "Director of Statistician",
  "Director of Strategy Manager",
  "Director of Support Engineer",
  "Director of Support Manager",
  "Director of Systems Engineer",
  "Director of Talent Acquisition Specialist",
  "Director of Teacher",
  "Director of Teaching Assistant",
  "Director of Technical Lead",
  "Director of Technical Product Manager",
  "Director of Technical Program Manager",
  "Director of Technical Recruiter",
  "Director of Technical Support Engineer",
  "Director of Technical Writer",
  "Director of Test Engineer",
  "Director of Trainer",
  "Director of Translator",
  "Director of Tutor",
  "Director of UI Designer",
  "Director of UX Designer",
  "Director of UX Researcher",
  "Director of Video Editor",
  "Director of Video Producer",
  "Director of Visual Designer",
  "Director of Web Designer",
  "Director of Web Developer",
  "Documentation Specialist",
  "Editor",
  "Education Consultant",
  "Email Marketing Manager",
  "Embedded Engineer",
  "Engineering Manager",
  "Enterprise Account Executive",
  "Entrepreneur",
  "Field Marketing Manager",
  "Finance Manager",
  "Financial Analyst",
  "Firmware Engineer",
  "Founder",
  "Freelancer",
  "Frontend Engineer",
  "Full Stack Engineer",
  "Game Developer",
  "General Manager",
  "Graphic Designer",
  "Group Product Manager",
  "Growth Marketer",
  "Growth Product Manager",
  "Head of Academic Advisor",
  "Head of Account Executive",
  "Head of Account Manager",
  "Head of Accountant",
  "Head of Agile Coach",
  "Head of AI Engineer",
  "Head of Analytics Engineer",
  "Head of Android Engineer",
  "Head of Art Director",
  "Head of Automation Engineer",
  "Head of Backend Engineer",
  "Head of BI Developer",
  "Head of Bookkeeper",
  "Head of Brand Designer",
  "Head of Brand Manager",
  "Head of Build Engineer",
  "Head of Business Analyst",
  "Head of Business Consultant",
  "Head of Business Development Representative",
  "Head of Business Operations Manager",
  "Head of Campaign Manager",
  "Head of Channel Manager",
  "Head of Chief of Staff",
  "Head of Cloud Engineer",
  "Head of Co-Founder",
  "Head of Communications Manager",
  "Head of Community Manager",
  "Head of Compliance Manager",
  "Head of Consultant",
  "Head of Content Creator",
  "Head of Content Marketer",
  "Head of Content Strategist",
  "Head of Content Writer",
  "Head of Contractor",
  "Head of Controller",
  "Head of Copywriter",
  "Head of Corporate Trainer",
  "Head of Course Creator",
  "Head of Creative Director",
  "Head of Curriculum Developer",
  "Head of Customer Experience Manager",
  "Head of Customer Service Representative",
  "Head of Customer Success Engineer",
  "Head of Customer Success Manager",
  "Head of Customer Support Specialist",
  "Head of Data Analyst",
  "Head of Data Architect",
  "Head of Data Engineer",
  "Head of Data Scientist",
  "Head of Database Administrator",
  "Head of Demand Generation Manager",
  "Head of Design Lead",
  "Head of Design Manager",
  "Head of Design Systems Designer",
  "Head of Developer Advocate",
  "Head of Developer Relations Manager",
  "Head of DevOps Engineer",
  "Head of Documentation Specialist",
  "Head of Editor",
  "Head of Education Consultant",
  "Head of Email Marketing Manager",
  "Head of Embedded Engineer",
  "Head of Engineering Manager",
  "Head of Enterprise Account Executive",
  "Head of Entrepreneur",
  "Head of Field Marketing Manager",
  "Head of Finance Manager",
  "Head of Financial Analyst",
  "Head of Firmware Engineer",
  "Head of Founder",
  "Head of Freelancer",
  "Head of Frontend Engineer",
  "Head of Full Stack Engineer",
  "Head of Game Developer",
  "Head of General Manager",
  "Head of Graphic Designer",
  "Head of Group Product Manager",
  "Head of Growth Marketer",
  "Head of Growth Product Manager",
  "Head of Help Desk Technician",
  "Head of HR Business Partner",
  "Head of HR Manager",
  "Head of Illustrator",
  "Head of Implementation Specialist",
  "Head of Inside Sales Representative",
  "Head of Insights Analyst",
  "Head of Instructional Designer",
  "Head of Instructor",
  "Head of Integration Engineer",
  "Head of Interaction Designer",
  "Head of Intern",
  "Head of iOS Engineer",
  "Head of Journalist",
  "Head of Knowledge Manager",
  "Head of Learning and Development Manager",
  "Head of Lecturer",
  "Head of Legal Counsel",
  "Head of Localization Manager",
  "Head of Machine Learning Engineer",
  "Head of Management Consultant",
  "Head of Marketing Manager",
  "Head of Marketing Operations Manager",
  "Head of Mobile Engineer",
  "Head of Motion Designer",
  "Head of Network Engineer",
  "Head of Office Manager",
  "Head of Onboarding Manager",
  "Head of Onboarding Specialist",
  "Head of Operations Analyst",
  "Head of Operations Manager",
  "Head of Owner",
  "Head of Paralegal",
  "Head of Partnerships Manager",
  "Head of Payroll Specialist",
  "Head of People Operations Manager",
  "Head of Performance Marketer",
  "Head of Platform Engineer",
  "Head of Podcast Producer",
  "Head of President",
  "Head of Product Analyst",
  "Head of Product Designer",
  "Head of Product Manager",
  "Head of Product Marketing Manager",
  "Head of Product Operations Manager",
  "Head of Product Owner",
  "Head of Professor",
  "Head of Program Manager",
  "Head of Project Manager",
  "Head of Public Relations Manager",
  "Head of QA Engineer",
  "Head of Quantitative Analyst",
  "Head of Recruiter",
  "Head of Release Engineer",
  "Head of Research Scientist",
  "Head of Researcher",
  "Head of Revenue Operations Manager",
  "Head of Sales Development Representative",
  "Head of Sales Director",
  "Head of Sales Engineer",
  "Head of Sales Manager",
  "Head of Sales Operations Manager",
  "Head of Sales Representative",
  "Head of School Administrator",
  "Head of Scrum Master",
  "Head of Security Engineer",
  "Head of SEO Specialist",
  "Head of Site Reliability Engineer",
  "Head of Social Media Manager",
  "Head of Software Architect",
  "Head of Software Engineer",
  "Head of Solutions Architect",
  "Head of Solutions Consultant",
  "Head of Solutions Engineer",
  "Head of Statistician",
  "Head of Strategy Manager",
  "Head of Support Engineer",
  "Head of Support Manager",
  "Head of Systems Engineer",
  "Head of Talent Acquisition Specialist",
  "Head of Teacher",
  "Head of Teaching Assistant",
  "Head of Technical Lead",
  "Head of Technical Product Manager",
  "Head of Technical Program Manager",
  "Head of Technical Recruiter",
  "Head of Technical Support Engineer",
  "Head of Technical Writer",
  "Head of Test Engineer",
  "Head of Trainer",
  "Head of Translator",
  "Head of Tutor",
  "Head of UI Designer",
  "Head of UX Designer",
  "Head of UX Researcher",
  "Head of Video Editor",
  "Head of Video Producer",
  "Head of Visual Designer",
  "Head of Web Designer",
  "Head of Web Developer",
  "Help Desk Technician",
  "HR Business Partner",
  "HR Manager",
  "Illustrator",
  "Implementation Specialist",
  "Inside Sales Representative",
  "Insights Analyst",
  "Instructional Designer",
  "Instructor",
  "Integration Engineer",
  "Interaction Designer",
  "Intern",
  "iOS Engineer",
  "Journalist",
  "Junior Academic Advisor",
  "Junior Account Executive",
  "Junior Account Manager",
  "Junior Accountant",
  "Junior Agile Coach",
  "Junior AI Engineer",
  "Junior Analytics Engineer",
  "Junior Android Engineer",
  "Junior Art Director",
  "Junior Automation Engineer",
  "Junior Backend Engineer",
  "Junior BI Developer",
  "Junior Bookkeeper",
  "Junior Brand Designer",
  "Junior Brand Manager",
  "Junior Build Engineer",
  "Junior Business Analyst",
  "Junior Business Consultant",
  "Junior Business Development Representative",
  "Junior Business Operations Manager",
  "Junior Campaign Manager",
  "Junior Channel Manager",
  "Junior Chief of Staff",
  "Junior Cloud Engineer",
  "Junior Co-Founder",
  "Junior Communications Manager",
  "Junior Community Manager",
  "Junior Compliance Manager",
  "Junior Consultant",
  "Junior Content Creator",
  "Junior Content Marketer",
  "Junior Content Strategist",
  "Junior Content Writer",
  "Junior Contractor",
  "Junior Controller",
  "Junior Copywriter",
  "Junior Corporate Trainer",
  "Junior Course Creator",
  "Junior Creative Director",
  "Junior Curriculum Developer",
  "Junior Customer Experience Manager",
  "Junior Customer Service Representative",
  "Junior Customer Success Engineer",
  "Junior Customer Success Manager",
  "Junior Customer Support Specialist",
  "Junior Data Analyst",
  "Junior Data Architect",
  "Junior Data Engineer",
  "Junior Data Scientist",
  "Junior Database Administrator",
  "Junior Demand Generation Manager",
  "Junior Design Lead",
  "Junior Design Manager",
  "Junior Design Systems Designer",
  "Junior Developer Advocate",
  "Junior Developer Relations Manager",
  "Junior DevOps Engineer",
  "Junior Documentation Specialist",
  "Junior Editor",
  "Junior Education Consultant",
  "Junior Email Marketing Manager",
  "Junior Embedded Engineer",
  "Junior Engineering Manager",
  "Junior Enterprise Account Executive",
  "Junior Entrepreneur",
  "Junior Field Marketing Manager",
  "Junior Finance Manager",
  "Junior Financial Analyst",
  "Junior Firmware Engineer",
  "Junior Founder",
  "Junior Freelancer",
  "Junior Frontend Engineer",
  "Junior Full Stack Engineer",
  "Junior Game Developer",
  "Junior General Manager",
  "Junior Graphic Designer",
  "Junior Group Product Manager",
  "Junior Growth Marketer",
  "Junior Growth Product Manager",
  "Junior Help Desk Technician",
  "Junior HR Business Partner",
  "Junior HR Manager",
  "Junior Illustrator",
  "Junior Implementation Specialist",
  "Junior Inside Sales Representative",
  "Junior Insights Analyst",
  "Junior Instructional Designer",
  "Junior Instructor",
  "Junior Integration Engineer",
  "Junior Interaction Designer",
  "Junior Intern",
  "Knowledge Manager",
  "Learning and Development Manager",
  "Lecturer",
  "Legal Counsel",
  "Localization Manager",
  "Machine Learning Engineer",
  "Management Consultant",
  "Marketing Manager",
  "Marketing Operations Manager",
  "Mobile Engineer",
  "Motion Designer",
  "Network Engineer",
  "Office Manager",
  "Onboarding Manager",
  "Onboarding Specialist",
  "Operations Analyst",
  "Operations Manager",
  "Owner",
  "Paralegal",
  "Partnerships Manager",
  "Payroll Specialist",
  "People Operations Manager",
  "Performance Marketer",
  "Platform Engineer",
  "Podcast Producer",
  "President",
  "Product Analyst",
  "Product Designer",
  "Product Manager",
  "Product Marketing Manager",
  "Product Operations Manager",
  "Product Owner",
  "Professor",
  "Program Manager",
  "Project Manager",
  "Public Relations Manager",
  "QA Engineer",
  "Quantitative Analyst",
  "Recruiter",
  "Release Engineer",
  "Research Scientist",
  "Researcher",
  "Revenue Operations Manager",
  "Sales Development Representative",
  "Sales Director",
  "Sales Engineer",
  "Sales Manager",
  "Sales Operations Manager",
  "Sales Representative",
  "School Administrator",
  "Scrum Master",
  "Security Engineer",
  "SEO Specialist",
  "Site Reliability Engineer",
  "Social Media Manager",
  "Software Architect",
  "Software Engineer",
  "Solutions Architect",
  "Solutions Consultant",
  "Solutions Engineer",
  "Statistician",
  "Strategy Manager",
  "Support Engineer",
  "Support Manager",
  "Systems Engineer",
  "Talent Acquisition Specialist",
  "Teacher",
  "Teaching Assistant",
  "Technical Lead",
  "Technical Product Manager",
  "Technical Program Manager",
  "Technical Recruiter",
  "Technical Support Engineer",
  "Technical Writer",
  "Test Engineer",
  "Trainer",
  "Translator",
  "Tutor",
  "UI Designer",
  "UX Designer",
  "UX Researcher",
  "Video Editor",
  "Video Producer",
  "Visual Designer",
  "Web Designer",
  "Web Developer",
];
